[package]
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
name = "cargo-deliver"
version = "0.2.0"

[dependencies]
duct = "0.9.2"
failure = "0.1.1"
failure_derive = "0.1.1"
lazy_static = "1.0.0"
rprompt = "1.0.3"
tera = "0.10.10"
