rust:
- target:
  {% for target in targets %}
    - {{ target }}
  {% endfor %}
  binary: {{ binary_name }}

# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Linux